name: Kubernetes Manifest Schema Validator (Kubeconform)

on:
  push:
    branches:
      - main
      - develop
      - feature/**
      - k8sValidate-test
      - candidate/**

jobs:
  validate_manifests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for accurate diffing

      - name: Identify Modified Kubernetes Manifest Files
        id: files
        run: |
          # Use git diff to find only the new or modified .yml files in the push
          files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.y[a]*ml$' | grep -E '(k8s/|lvl1/|lvl2/|lvl3/)' || true)
          
          if [ -z "$files" ]; then
            echo "::notice::Skipping validation: No Kubernetes manifest files modified in this push."
            echo "skip_validation=true" >> $GITHUB_OUTPUT
          else
            echo "k8s_files=$files" >> $GITHUB_OUTPUT
          fi
      
      - name: Run Kubeconform Setup
        if: steps.files.outputs.skip_validation != 'true'
        uses: bmuschko/setup-kubeconform@v1
        id: kubeconform_setup
        with:
          kubeconform-version: '0.6.1'

      - name: Run Kubeconform Validation
        # Runs only if there are files to validate
        id: kubeconform
        run: |
            kubeconform -summary -output json -strict -verbose ${{ steps.files.outputs.k8s_files }}
      - name: Echo previous output for debug
        run: |
          echo "${{ steps.kubeconform.outcome }}"
          
      - name: Comment on Successful Manifest Validation
        # Runs if the entire job succeeded (files were checked and passed)
        if: steps.kubeconform.conclusion == 'success' && steps.files.outputs.skip_validation != 'true'
        uses: peter-evans/commit-comment@v4
        with:
          body: |
            ✅ **Kubernetes Manifest Validation Success**
            All modified manifests passed the manifest analisys. The file syntax is correct and conforms to the cluster schema.
            ${{
              steps.kubeconform.outputs.validation_result
            }}
          
      - name: Comment on Failed Manifest Validation
        # Runs if the job failed when files contains errors
        if: failure() && steps.files.outputs.skip_validation != 'true'
        uses: peter-evans/commit-comment@v4
        with:
          body: |
            🚨 **Kubernetes Manifest Validation Failed**
            The GitHub Action failed due to errors found during K8s manifest analysis with Kubeconform.
            
            Please check the **`Run Kubeconform Validation`** step output in the workflow logs for details on:
            1.  **YAML Syntax Errors**
            2.  **Kubernetes Schema Errors** (e.g., misspelled field names, invalid resource kind, or missing required fields).